# User ctrl + space as super key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Enable renumber window to avoid bad order when create a new one
set -g renumber-windows on

# Move bar to the top
set -g status-position top

# Bind keys
# Bind keys to navigate between panes/windows (based on availability) with 'vim motions'
bind h if-shell "[ $(tmux display-message -p '#{pane_at_left}') -eq 0 ]" 'select-pane -L' 'previous-window'
bind l if-shell "[ $(tmux display-message -p '#{pane_at_right}') -eq 0 ]" 'select-pane -R' 'next-window'
bind k 'select-pane -U'
bind j 'select-pane -D'

unbind &
bind q kill-window
# END Bind keys

# TPM conficcg
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# TMUX Theme configuration
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' # 'dark256', 'light', 'light256'

run '~/.tmux/plugins/tpm/tpm'
# END TPM config
